# Generated by Django 4.2 on 2026-10-02 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quality_program_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('fabric_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=1)),
                ('updated_by', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Quality Program',
                'verbose_name_plural': 'Quality Programs',
                'db_table': 'quality_program',
            },
        ),
        migrations.CreateModel(
            name='sub_quality_program_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('per_box', models.IntegerField()),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=1)),
                ('updated_by', models.IntegerField(default=1)),
                ('tm', models.ForeignKey(db_column='tm_id', on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='masters.quality_program_table', verbose_name='Quality Program')),
            ],
            options={
                'verbose_name': 'Sub Quality Program Size',
                'verbose_name_plural': 'Sub Quality Program Sizes',
                'db_table': 'mx_quality_program_size',
            },
        ),
    ]
