# Generated by Django 4.2 on 2026-10-02 12:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_quality_program_table_sub_quality_program_table'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_yarn_inward_table',
            name='dyeing_charges',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total dyeing charges', max_digits=20),
        ),
        migrations.AddField(
            model_name='parent_yarn_inward_table',
            name='dyeing_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dyeing job work rate per Kg', max_digits=20),
        ),
        migrations.AddField(
            model_name='parent_yarn_inward_table',
            name='inward_source',
            field=models.CharField(choices=[('PURCHASE_PO', 'Yarn PO Receipt'), ('DYEING_RETURN', 'Dyeing Return (Job Work)')], db_index=True, default='PURCHASE_PO', help_text='Source of Yarn Inward', max_length=20),
        ),
        migrations.AddField(
            model_name='parent_yarn_inward_table',
            name='outward',
            field=models.ForeignKey(blank=True, db_column='outward_id', help_text='Associated Yarn Outward for Dyeing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inwards', to='inventory.parent_yarn_outward_table'),
        ),
        migrations.AddField(
            model_name='parent_yarn_inward_table',
            name='process_loss_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dyeing process loss %', max_digits=5),
        ),
        migrations.AddField(
            model_name='parent_yarn_inward_table',
            name='process_loss_wt',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Dyeing process loss in Kg', max_digits=20),
        ),
        migrations.AddField(
            model_name='parent_yarn_outward_table',
            name='is_complete',
            field=models.IntegerField(default=0, help_text='0 = In-progress at processor, 1 = Fully received / completed'),
        ),
        migrations.AddField(
            model_name='parent_yarn_outward_table',
            name='received_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Received weight from dyeing/knitting (Kg)', max_digits=20),
        ),
        migrations.AddField(
            model_name='parent_yarn_outward_table',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Pending weight at processor (Kg)', max_digits=20),
        ),
        migrations.AlterField(
            model_name='parent_yarn_inward_table',
            name='party',
            field=models.ForeignKey(help_text='Supplier / Trader / Dyeing Unit', on_delete=django.db.models.deletion.PROTECT, related_name='yarn_inward_parties', to='masters.partymaster'),
        ),
    ]
