# Generated by Django 4.2 on 2026-10-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_privilege_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='module',
            field=models.CharField(choices=[('company_management', 'Company Management'), ('financial_year_management', 'Financial Year Management'), ('user_management', 'Admin User Management'), ('employee_management', 'Employee / Company User Management'), ('role_management', 'Role & Privilege Management'), ('masters_party', 'Party Master (Mills, Traders, Customers, Suppliers)'), ('masters_yarn', 'Yarn Master'), ('masters_fabric', 'Fabric Master'), ('masters_process', 'Process Master'), ('masters_uom', 'Unit of Measurement'), ('masters_color', 'Color / Shade Master'), ('masters_warehouse', 'Warehouse / Location Master'), ('purchase_yarn_po', 'Yarn Purchase Order'), ('inventory_yarn_inward', 'Yarn Inward (GRN)'), ('inventory_yarn_outward', 'Yarn Outward (Knitting/Dyeing/Return)'), ('inventory_yarn_stock', 'Yarn Stock Ledger'), ('sales_yarn', 'Yarn Sales'), ('sales_yarn_return', 'Yarn Sales Return')], max_length=100),
        ),
    ]
