# Generated by Django 4.2 on 2026-10-02 08:47

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_privilege_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0002_quality_program_table_sub_quality_program_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='yarn_po_balance_table',
            fields=[
                ('po_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=30)),
                ('yarn_type', models.CharField(max_length=20)),
                ('yarn_count_id', models.IntegerField()),
                ('party_id', models.IntegerField()),
                ('ord_bags', models.IntegerField()),
                ('po_quantity', models.DecimalField(decimal_places=3, max_digits=20)),
                ('in_bag', models.IntegerField(default=0)),
                ('in_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('balance_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Yarn PO Balance',
                'verbose_name_plural': 'Yarn PO Balances',
                'db_table': 'yarn_po_balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='yarn_po_delivery_sum_table',
            fields=[
                ('tm_po_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('party_id', models.IntegerField()),
                ('destination_name', models.CharField(max_length=255)),
                ('total_delivery_bags', models.IntegerField()),
                ('total_delivery_quantity', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
            options={
                'verbose_name': 'Yarn PO Delivery Summary',
                'verbose_name_plural': 'Yarn PO Delivery Summaries',
                'db_table': 'y_po_sum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='yarn_po_sum_table',
            fields=[
                ('tm_po_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('yarn_count_id', models.IntegerField()),
                ('yarn_type', models.CharField(max_length=20)),
                ('total_ordered_bags', models.IntegerField()),
                ('total_ordered_quantity', models.DecimalField(decimal_places=3, max_digits=20)),
                ('total_received_bags', models.IntegerField(default=0)),
                ('total_received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Yarn PO Summary',
                'verbose_name_plural': 'Yarn PO Summaries',
                'db_table': 'yarn_po_sum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='parent_po_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('po_date', models.DateField(db_index=True)),
                ('yarn_type', models.CharField(choices=[('GREY', 'Grey Yarn'), ('DYED', 'Dyed Yarn')], db_index=True, default='GREY', help_text='Yarn Type: GREY (Grey Yarn) or DYED (Dyed Yarn)', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Order reference name / description', max_length=50, null=True)),
                ('bag', models.IntegerField(default=0, help_text='Total number of bags ordered')),
                ('per_bag', models.DecimalField(decimal_places=3, default=Decimal('45.360'), help_text='Standard weight per bag in Kg (typically 45.360 or 50.000)', max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total Net Quantity in Kg (bag * per_bag)', max_digits=20)),
                ('gross_quantity', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), help_text='Gross weight including packing tare', max_digits=20, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base rate per Kg', max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount per Kg or flat discount', max_digits=20)),
                ('net_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final rate after discount (rate - discount)', max_digits=20)),
                ('amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total net order value (quantity * net_rate)', max_digits=20)),
                ('remarks', models.CharField(blank=True, help_text='Delivery terms, CSP specs, or payment terms', max_length=150, null=True)),
                ('is_delivery', models.IntegerField(default=0, help_text='Flag (0/1): indicates if scheduled split delivery is enabled')),
                ('is_complete', models.IntegerField(default=0, help_text='0 = Pending / In-progress, 1 = Fully received')),
                ('is_authorized', models.IntegerField(default=0, help_text='Approval lock (0 = Draft, 1 = Authorized)')),
                ('authorized_on', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1, help_text='1 = Active, 0 = Inactive')),
                ('status', models.IntegerField(default=1, help_text='Record status (1 = Valid, 0 = Soft Deleted)')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(blank=True, db_column='authorized_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_yarn_pos', to=settings.AUTH_USER_MODEL)),
                ('cfyear', models.ForeignKey(db_column='cfyear', help_text='Active Financial Year reference', on_delete=django.db.models.deletion.PROTECT, related_name='yarn_pos', to='authentication.financialyear')),
                ('color_shade', models.ForeignKey(blank=True, help_text='Required if yarn_type is DYED', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yarn_pos', to='masters.colorshademaster')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='yarn_pos', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_yarn_pos', to=settings.AUTH_USER_MODEL)),
                ('mill', models.ForeignKey(db_column='mill_id', help_text='Spinning Mill where yarn is spun', on_delete=django.db.models.deletion.PROTECT, related_name='yarn_po_mills', to='masters.partymaster')),
                ('party', models.ForeignKey(db_column='party_id', help_text='Yarn Supplier / Trader / Agent', on_delete=django.db.models.deletion.PROTECT, related_name='yarn_po_parties', to='masters.partymaster')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_yarn_pos', to=settings.AUTH_USER_MODEL)),
                ('yarn_count', models.ForeignKey(blank=True, db_column='yarn_count_id', help_text='Primary Yarn Count (e.g. 30s Combed, 34s Carded)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yarn_pos', to='masters.yarncountmaster')),
            ],
            options={
                'verbose_name': 'Yarn Purchase Order',
                'verbose_name_plural': 'Yarn Purchase Orders',
                'db_table': 'tm_yarn_po',
                'ordering': ['-po_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='yarn_po_delivery_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(help_text='Expected arrival date')),
                ('bag', models.IntegerField(default=0, help_text='Scheduled bag count')),
                ('bag_wt', models.DecimalField(decimal_places=3, default=Decimal('45.360'), help_text='Weight per bag (Kg)', max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Scheduled quantity (bag * bag_wt)', max_digits=20)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('cfyear', models.ForeignKey(db_column='cfyear', on_delete=django.db.models.deletion.PROTECT, related_name='po_deliveries', to='authentication.financialyear')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='po_deliveries', to='authentication.company')),
                ('party', models.ForeignKey(db_column='party_id', help_text='Destination Party (Knitting Mill or Own Warehouse)', on_delete=django.db.models.deletion.PROTECT, related_name='po_deliveries', to='masters.partymaster')),
                ('tm_po', models.ForeignKey(db_column='tm_po_id', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='purchase.parent_po_table')),
                ('yarn_count', models.ForeignKey(db_column='yarn_count_id', on_delete=django.db.models.deletion.PROTECT, related_name='po_deliveries', to='masters.yarncountmaster')),
            ],
            options={
                'verbose_name': 'Yarn PO Delivery Schedule',
                'verbose_name_plural': 'Yarn PO Delivery Schedules',
                'db_table': 'tx_yarn_po',
                'ordering': ['delivery_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='child_po_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yarn_type', models.CharField(choices=[('GREY', 'Grey Yarn'), ('DYED', 'Dyed Yarn')], default='GREY', help_text='Grey Yarn or Dyed Yarn', max_length=20)),
                ('bag', models.IntegerField(default=0, help_text='Number of bags ordered for this count')),
                ('per_bag', models.DecimalField(decimal_places=3, default=Decimal('45.360'), help_text='Weight per bag in Kg', max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total Net Quantity (bag * per_bag)', max_digits=20)),
                ('gross_wt', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), help_text='Gross weight', max_digits=20, null=True)),
                ('actual_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Mill catalogue / base rate per Kg', max_digits=20)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount per Kg', max_digits=20)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Effective rate per Kg (actual_rate - discount)', max_digits=20)),
                ('amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Line item total (quantity * rate)', max_digits=20)),
                ('remaining_bag', models.IntegerField(default=0, help_text='Pending unreceived bags')),
                ('remaining_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Pending unreceived weight (Kg)', max_digits=20)),
                ('remaining_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Pending commercial liability', max_digits=20)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('color_shade', models.ForeignKey(blank=True, db_column='color_shade_id', help_text='Color shade if Dyed Yarn', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_line_items', to='masters.colorshademaster')),
                ('tm_po', models.ForeignKey(db_column='tm_po_id', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase.parent_po_table')),
                ('yarn_count', models.ForeignKey(db_column='yarn_count_id', on_delete=django.db.models.deletion.PROTECT, related_name='po_line_items', to='masters.yarncountmaster')),
            ],
            options={
                'verbose_name': 'Yarn PO Line Item',
                'verbose_name_plural': 'Yarn PO Line Items',
                'db_table': 'tx_purchase_order',
            },
        ),
        migrations.AddIndex(
            model_name='parent_po_table',
            index=models.Index(fields=['company', 'po_number'], name='tm_yarn_po_company_2a6e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='parent_po_table',
            index=models.Index(fields=['yarn_type', 'is_authorized', 'is_complete'], name='tm_yarn_po_yarn_ty_cde6cc_idx'),
        ),
    ]
