# Generated by Django 4.2 on 2026-10-02 10:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_quality_program_table_sub_quality_program_table'),
        ('authentication', '0003_alter_privilege_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='parent_yarn_sales_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('invoice_date', models.DateField(db_index=True)),
                ('yarn_type', models.CharField(choices=[('GREY', 'Grey Yarn'), ('DYED', 'Dyed Yarn')], db_index=True, default='GREY', max_length=20)),
                ('lot_no', models.CharField(default='GEN', max_length=50)),
                ('bag', models.IntegerField(default=0)),
                ('per_bag', models.DecimalField(decimal_places=3, default=Decimal('45.360'), max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Net sold weight (Kg)', max_digits=20)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sale rate per Kg', max_digits=20)),
                ('subtotal', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='GST % (typically 5% for Yarn)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('is_authorized', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('cfyear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yarn_sales', to='authentication.financialyear')),
                ('color_shade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yarn_sales', to='masters.colorshademaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yarn_sales', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_yarn_sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Buyer / Customer', on_delete=django.db.models.deletion.PROTECT, related_name='yarn_sales_customers', to='masters.partymaster')),
                ('mill', models.ForeignKey(help_text='Spinning Mill', on_delete=django.db.models.deletion.PROTECT, related_name='yarn_sales_mills', to='masters.partymaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_yarn_sales', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yarn_sales', to='masters.warehousemaster')),
                ('yarn_count', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yarn_sales', to='masters.yarncountmaster')),
            ],
            options={
                'verbose_name': 'Yarn Sales',
                'verbose_name_plural': 'Yarn Sales',
                'db_table': 'tm_yarn_sales',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='parent_yarn_sales_return_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('return_date', models.DateField(db_index=True)),
                ('yarn_type', models.CharField(choices=[('GREY', 'Grey Yarn'), ('DYED', 'Dyed Yarn')], db_index=True, default='GREY', max_length=20)),
                ('lot_no', models.CharField(default='GEN', max_length=50)),
                ('bag', models.IntegerField(default=0)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Returned weight in Kg', max_digits=20)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20)),
                ('return_reason', models.CharField(help_text='E.g., Shade Variation, Defective Count, Excess Quantity', max_length=200)),
                ('is_authorized', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('cfyear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yarn_sales_returns', to='authentication.financialyear')),
                ('color_shade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yarn_sales_returns', to='masters.colorshademaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yarn_sales_returns', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_yarn_sales_returns', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yarn_sales_return_customers', to='masters.partymaster')),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yarn_sales_return_mills', to='masters.partymaster')),
                ('sales_invoice', models.ForeignKey(blank=True, help_text='Reference Sales Invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='sales.parent_yarn_sales_table')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_yarn_sales_returns', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yarn_sales_returns', to='masters.warehousemaster')),
                ('yarn_count', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='yarn_sales_returns', to='masters.yarncountmaster')),
            ],
            options={
                'verbose_name': 'Yarn Sales Return',
                'verbose_name_plural': 'Yarn Sales Returns',
                'db_table': 'tm_yarn_sales_return',
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='child_yarn_sales_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(default='GEN', max_length=50)),
                ('bag', models.IntegerField(default=0)),
                ('per_bag', models.DecimalField(decimal_places=3, default=Decimal('45.360'), max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20)),
                ('status', models.IntegerField(default=1)),
                ('color_shade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_line_items', to='masters.colorshademaster')),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_line_items', to='masters.partymaster')),
                ('tm_sales', models.ForeignKey(db_column='tm_sales_id', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='sales.parent_yarn_sales_table')),
                ('yarn_count', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_line_items', to='masters.yarncountmaster')),
            ],
            options={
                'verbose_name': 'Yarn Sales Line Item',
                'verbose_name_plural': 'Yarn Sales Line Items',
                'db_table': 'tx_yarn_sales',
            },
        ),
        migrations.CreateModel(
            name='child_yarn_sales_return_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(default='GEN', max_length=50)),
                ('bag', models.IntegerField(default=0)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20)),
                ('status', models.IntegerField(default=1)),
                ('color_shade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_line_items', to='masters.colorshademaster')),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_line_items', to='masters.partymaster')),
                ('tm_sales_return', models.ForeignKey(db_column='tm_sales_return_id', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='sales.parent_yarn_sales_return_table')),
                ('yarn_count', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_line_items', to='masters.yarncountmaster')),
            ],
            options={
                'verbose_name': 'Yarn Sales Return Line Item',
                'verbose_name_plural': 'Yarn Sales Return Line Items',
                'db_table': 'tx_yarn_sales_return',
            },
        ),
    ]
